stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the application..."
    - bash ./sample-app.sh
  tags:
    - shell

test:
  stage: test
  script:
    - echo "Testing the application..."
    - curl http://localhost:5050/ | grep "You are calling me from"
  tags:
    - shell

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - docker run --name samplerunning -d -p 5050:5050 your-docker-image
  tags:
    - shell

