image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t sampleapp .
  artifacts:
    paths:
      - tempdir

deploy:
  stage: deploy
  script:
    - echo "Deploying Docker container..."
    - docker run -d -p 5050:5050 --name samplerunning sampleapp
  only:
    - main